#!/bin/bash 

   echo "welcome to prime problem"
   function checkprime( ) {
     number=$1
     for (( i=2; i<$number; i++ ))
       do
         if [[ $(($number%$i)) -eq 0 ]]
         then
             flag=1
         fi
       done
       if [[ $flag -eq 0 ]]
       then
           savetoarray
       fi
       flag=0
       }
   function savetoarray( ) {
   primesarray[$k]=$i
   count=$(($count+1))
   k=$(($k+1))
   }
   function initialize( ) {
    count=0
    flag=0
    k=0
    i=2
    while (( $count != 100 ))
    do
    checkprime $i
    i=$((i+1))
    done
   }
   function printreverseorder( ) {
   
   for ((  j=99; j>=0; j-- ))
   do 
   echo "${primesarray[$j]}"
   done
   }
   #Print 50 alternate primes in reverse order
   function print50primes( ) {
   for (( m=99; m>=0; m=$(($m-2)) ))
   do
   echo "${primesarray[$m]}"
   done
   }
   function main( ) {
   initialize
   printreverseorder
   echo "print 50 alternative primes in reverse order"
   print50primes
   }

   main
